# Generated by Django 4.1.1 on 2022-10-12 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='category_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('cat_image', models.ImageField(null=True, upload_to='image/')),
            ],
        ),
        migrations.CreateModel(
            name='weight_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('descripion', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('product_image', models.ImageField(null=True, upload_to='image/')),
                ('catg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery_app.category_tbl')),
                ('wgt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery_app.weight_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='multi_image_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_image', models.ImageField(null=True, upload_to='image/')),
                ('prodt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery_app.product_tbl')),
            ],
        ),
        migrations.CreateModel(
            name='customer_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=150)),
                ('cust_phone', models.CharField(max_length=12)),
                ('cust_image', models.ImageField(null=True, upload_to='image/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cust', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery_app.customer_tbl')),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery_app.product_tbl')),
                ('wght', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery_app.weight_tbl')),
            ],
        ),
    ]
