# Generated by Django 4.1.1 on 2022-10-12 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=225)),
                ('subject', models.CharField(max_length=225)),
                ('message', models.CharField(max_length=225)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
