# Generated by Django 4.1.1 on 2022-10-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0002_mail_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight_tbl',
            name='weight',
            field=models.CharField(max_length=12),
        ),
    ]
