# Generated by Django 4.1.1 on 2022-10-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery_app', '0003_alter_weight_tbl_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tbl',
            old_name='descripion',
            new_name='description',
        ),
    ]
