# Generated by Django 4.1.1 on 2022-10-15 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bakery_app', '0004_rename_descripion_product_tbl_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_tbl',
            name='cust',
        ),
        migrations.AddField(
            model_name='cart_tbl',
            name='cart_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
